#server info
spring:
   application:
      name: /eureka
server:
   host: localhost
   port: 9090
#spring cloud eureka
eureka:
   instance:
      prefer-ip-address: true
   client:
      fetch-registry: false
      register-with-eureka: false
      service-url:
         defaultZone: http://${server.host}:${server.port}
#logback
logging:
   config: classpath:config/logback-spring.xml