#server info
server:
   port: 8081
#spring cloud eureka
eurekaServer:
   host: localhost
   port: 9090
eureka:
   client:
      register-with-eureka: true
      service-url:
         defaultZone: http://${eurekaServer.host}:${eurekaServer.port}/eureka
#application info
spring:
   application:
      name: nogame-primary-service
#JDBC info
   datasource:
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://127.0.0.1:3306/nogame?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: root
#mapper scan path
mybatis:
   mapper-locations: classpath*:mappers/*Mapper.xml
#SCAN MAPPER ENTITY
   type-aliases-package: com.nogame.primary
#show SQl
logging:
   level:
      com:
         example:
            mapper: debug